### ISSUE TITLE
Define code style

### ISSUE THREAD

**Issue by fatihi** [fatihi/fiveringsdb#13]

**Comment by Fuzzylog1cza** [comment]
Stylecop springs to mind.

**Comment by programming-wolf** [comment]
EditorConfig is just too limited.

**Comment by jamesoddy** [comment]
EditorConfig has the advantage of being open source and IDE independent, but I am not familiar with the others mentioned here.

It does look as though Rider supports editorconfig https://www.jetbrains.com/help/rider/Using_EditorConfig.html

**Comment by Fuzzylog1cza** [comment]
Couple of pros and cons of all examples, I'd just like to lay them out:

1.  Stylecop can be hooked into the CI so it runs on build including running it on dotnet build. There is also a resharper extension for it so any rules prescribed in stylecop bubble up to resharper. The con is that many IDE's dont support it and you will only get the errors when you try build instead of as you type. Note using anything that supports resharper will automatically support stylecop by using the resharper-stylecop extension.

2.  Resharper is a brilliant feature rich tool. VS Code and other smaller IDEs don't support it but it's built into Rider (free for open source) and install-able in Visual Studio (community edition is free but the resharper license isn't)

3.  Editor Config has a wide range of IDE's it supports and is 100% opensource but it has the least features.

I'd suggest we use Stylecop at least at a CI level, all of those who can use Resharper should add the stylcop extension. All others should use EditorConfig with the rules files matching the stylecop rules file. This means that anyone who builds will catch the failures and there are two ways of catching the failures before build within their IDE of choice.

**Comment by programming-wolf** [comment]
Resharper license should be free for open source as well (https://www.jetbrains.com/buy/opensource/).

And I agree with your proposal, @Fuzzylog1cza. If we have automated builds for feature branches, everyone will see the style cop errors at least there.

**Comment by jamesoddy** [comment]
@Fuzzylog1cza that sounds like a really good solution.

**Comment by Fuzzylog1cza** [comment]
I've added in Stylecop and FXCop. Someone could still look at the VS Code experience but right now a dotnet build will tell you where you went wrong.

Can we consider this closed?

**Comment by fatihi** [comment]
Yeah I think that's fine. If someone is not happy with the solution, we can still open the issue again.
